#!/usr/bin/env python3
# List the Databases

import pymongo


def list_databases():
    """List all databases in MongoDB."""
    client = pymongo.MongoClient("mongodb://localhost:27017/")
    databases = client.list_database_names()


    for database in databases:
        print(database)

if __name__ == "__main__":
    list_databases()
